### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [cherryBotha/f1-3-c2p1-colmar-academy#2]
This is for the desktop version since I can't judge this as a whole project.

Overall Excellent.

The HTML and CSS is well done.  You have your html comment.  Organized in a manner that makes sense, your classes are meaningful to the section you are doing.  I do have to say I don't like the class it_doesn't_hurt.  It sounds like a dentist website.

The CSS isn't repetitive which is great.  You have that commented also which helps going through all this.  You used rem through out which is what I look for in a forward moving website.

As a final challenge take a look at progressive web apps https://developers.google.com/web/progressive-web-apps/

See if you can convert this into one as this is a future direction that websites are moving too.

**Comment by cherryBotha** [comment]
thank you for your feedback on my project @farishkash .
